openapi: 3.0.3
info:
  title: TD Final API STD23001 / Football Competition Management 
  version: 1.0.0
  description: API for managing football competitions, teams, and players.

paths:
  /competitions:
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '201':
          description: Competition created successfully
    get:
      summary: Get a list of competitions
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'

  /teams:
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully
    get:
      summary: Get a list of teams
      parameters:
        - name: teamName
          in: query
          schema:
            type: string
            description: Filter teams by name
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

  /players:
    post:
      summary: Create a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '201':
          description: Player created successfully
    get:
      summary: Get a list of players
      parameters:
        - name: teamId
          in: query
          schema:
            type: string
        - name: playerName
          in: query
          schema:
            type: string
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: LIGA
        country:
          type: string
          example: ESPAGNE
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'

    Team:
      type: object
      properties:
        name:
          type: string
          example: Real Madrid
        motto:
          type: string
          example: "Victory or Nothing"
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        fullName:
          type: string
          example: Lionel Messi
        jerseyNumber:
          type: integer
          example: 10
        dominantFoot:
          type: string
          enum: [Left, Right]

    TeamWithPlayers:
      type: object
      properties:
        name:
          type: string
        motto:
          type: string
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
